CREATE TABLE games (
  id INT PRIMARY KEY AUTO_INCREMENT,
  player VARCHAR(64) REFERENCES users(id),
  moves JSON NOT NULL,
  result VARCHAR(256) NOT NULL,

  played_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
